name: Deploy to dev
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: # Deploy Manually

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    name: Deploy to dev
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@v3
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t deploy/template.yaml --lint

      - name: "Push image and template"
        uses: govuk-one-login/devplatform-upload-action-ecr@v1.3.0
        with:
          artifact-bucket-name: ${{ secrets.DEV_ARTIFACT_BUCKET_NAME }}
          container-sign-kms-key-arn: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
          template-file: deploy/template.yaml
          docker-build-path: .
          dockerfile: dev.Dockerfile
          role-to-assume-arn: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
          ecr-repo-name: ${{ secrets.DEV_ECR_NAME_FRONT }}
